> ### **Assignment 2 - Numpy Array Operations** 
>


Write a short introduction about Numpy and list the chosen functions. 

function1 = np.append 

function2 = np.average

function3 = np.arange

function4 = np.squeeze

function5 = np.vstack




In [5]:
import numpy as np

## Function 1 - np.append
np.append function add elements to the end of an array provided that the dimensions of the elements should be same.

In [6]:
# Example 1 - working (change this)
arr1 = [1, 2, 1, 25, 26]
np.append(arr1, [24, 23, 15])


array([ 1,  2,  1, 25, 26, 24, 23, 15])

We can put lists as an element inside the array, then append it with the expected lists or any element regardless of their size.



In [7]:
# Example 2 - working
arr2 = [[2, 4, 5], [6, 7, 8]]
np.append(arr2, [10, 12])
np.append(arr2, [10, 12, 13, 14])

array([ 2,  4,  5,  6,  7,  8, 10, 12, 13, 14])

When axis is specified, arrays must have the same shape.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [14, 15, 16], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Some closing comments about when to use this function.

In [ ]:
# Fix
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [[14, 15, 16], [12, 15, 16]], axis = 0)

In arr3, index 0 has 2 dimensions, while the element to be appended has 1 dimension, thus breaks down. To fix this, the element to be appended should have 2 dimensions as well.

## Function 2 - np.average

The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.

In [ ]:
# Example 1 - working
ar1 = [1, 2, 1, 25, 26]

In [ ]:
np.average(ar1)

np.average() function computes the weighted average of element in an array according to their respective weight.

In [ ]:
# Example 2 - working
ar2 = np.array([[1, 3, 5],
              [1, 1, 1],
              [0, 2, 4]])


In [ ]:
ar2

In [ ]:
np.average(data)

Here i've created a matrix and found the average i.e we can find average for matrix also

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
np.average(data, weights=[1./4, 3./4])

NameError: name 'data' is not defined

In [ ]:
data = np.arange(6).reshape((3,2))

In [ ]:
# Fix
np.average(data,axis=1, weights=[1./4, 3./4])

## Function 3 - np.arange


The np. arange is a Numpy method that returns the ndarray object containing evenly spaced values within the given range. The numpy arange() function takes four parameters: start, stop, step, and dtype and returns evenly spaced values within a given interval.

In [ ]:
# Example 1 - working
ar3=np.arange(1,50,5)

In [ ]:
ar3

The np.arange is a Numpy method that returns the ndarray object contining evenly spaced values within the given range. 

In [ ]:
# Example 2 - working
ar3.reshape(5,2)

We can reshape the generated array as a matrix 

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

## Function 4 - Squeeze

squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.

In [10]:
# Example 1 - working
ar4 = np.array([[[0], [1], [2]]])


In [11]:
ar4

array([[[0],
        [1],
        [2]]])

In [12]:
np.size(ar4)

3

In [13]:
np.squeeze(ar4).shape

(3,)

Explanation about example

In [14]:
# Example 2 - working
???

Object `?` not found.


Explanation about example

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
np.squeeze(ar4, axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [ ]:
##Fix


np.squeeze(ar4, axis=2).shape

## Function 5 - np.vstack

vstack() function is used to stack the sequence of input arrays vertically to make a single array.

In [ ]:
# Example 1 - working
ar5 = np.array([[5], [26], [35]])

In [ ]:
ar6 = np.array([[45], [45], [46]])

In [ ]:
np.vstack((ar5,ar6))

Here we are stacking 2D array

In [ ]:
# Example 2 - working
ar7 = np.array([15, 25, 35])

In [ ]:

ar8 = np.array([45, 55, 56])

In [ ]:
np.vstack((ar7,ar8))

Here we are stacking 1D array

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)


In [ ]:
#Fix